# Generated by Django 5.0.4 on 2024-04-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rooter", models.CharField(max_length=100000)),
                ("user", models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリー")),
            ],
        ),
        migrations.CreateModel(
            name="CommentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classname", models.CharField(max_length=1000000)),
                ("comment", models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name="FollowCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=1000000)),
                ("user", models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name="FollowersCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=10000)),
                ("follower", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="Root",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=10000000)),
                ("rooter", models.CharField(max_length=1000000)),
                ("user", models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        null=True,
                        verbose_name="ユーザー名",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="image/", verbose_name="バックイメージ"),
                ),
                ("icon", models.ImageField(upload_to="icon/", verbose_name="アイコン")),
                (
                    "infomation",
                    models.TextField(
                        blank=True, max_length=180, null=True, verbose_name="紹介文"
                    ),
                ),
                (
                    "hobby",
                    models.CharField(
                        choices=[
                            ("PC", "PC"),
                            ("読書", "読書"),
                            ("TV", "TV"),
                            ("運動", "運動"),
                            ("ゲーム", "ゲーム"),
                            ("VR/AR", "VR/AR"),
                            ("映画", "映画"),
                            ("プログラミング", "プログラミング"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        choices=[
                            ("社会人", "社会人"),
                            ("大学生", "大学生"),
                            ("中学生", "中学生"),
                            ("高校生", "高校生"),
                            ("小学生", "小学生"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日"
                    ),
                ),
                (
                    "mainuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="メインユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Account",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Class名"
                    ),
                ),
                ("web_site", models.URLField(blank=True)),
                (
                    "backimage",
                    models.ImageField(upload_to="backimage/", verbose_name="BackImage"),
                ),
                (
                    "icon",
                    models.ImageField(
                        null=True, upload_to="classicon/", verbose_name="クラスアイコン"
                    ),
                ),
                (
                    "index",
                    models.CharField(max_length=50, null=True, verbose_name="見出し"),
                ),
                (
                    "explain",
                    models.TextField(
                        blank=True, max_length=180, verbose_name="explain"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, null=True, verbose_name="作成日"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="xlink.category",
                        verbose_name="ジャンル",
                    ),
                ),
                (
                    "mainuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="メインユーザー",
                    ),
                ),
                (
                    "managername",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xlink.account",
                        verbose_name="管理者",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ClassName",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=200, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="post/")),
                ("video", models.FileField(blank=True, null=True, upload_to="video/")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日"
                    ),
                ),
                (
                    "mainuser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="メインユーザー",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xlink.account",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="投稿先",
                        to="xlink.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="xlink.group"
                    ),
                ),
                (
                    "recommending_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=158, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日"
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xlink.group",
                        verbose_name="class先",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returncomments",
                        to="xlink.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xlink.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ReturnComments",
            },
        ),
        migrations.CreateModel(
            name="Rooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
