# Generated by Django 5.0.4 on 2024-04-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="detail",
            field=models.CharField(
                choices=[
                    ("中学生", "中学生"),
                    ("小学生", "小学生"),
                    ("社会人", "社会人"),
                    ("大学生", "大学生"),
                    ("・・・・", "・・・・"),
                    ("高校生", "高校生"),
                ],
                default="・・・・",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="hobby",
            field=models.CharField(
                choices=[
                    ("VR/AR", "VR/AR"),
                    ("TV", "TV"),
                    ("・・・・", "・・・・"),
                    ("読書", "読書"),
                    ("PC", "PC"),
                    ("映画", "映画"),
                    ("ゲーム", "ゲーム"),
                    ("プログラミング", "プログラミング"),
                    ("運動", "運動"),
                ],
                default="・・・・",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="icon",
            field=models.ImageField(
                default="/media/defult/5770f01a32c3c53e90ecda61483ccb08.jpg",
                upload_to="icon/",
                verbose_name="アイコン",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default="/media/defult/real-grayscale-marble-texture-background_37787-1754.jpg",
                upload_to="image/",
                verbose_name="バックイメージ",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="infomation",
            field=models.TextField(
                blank=True,
                default="・・・・",
                max_length=180,
                null=True,
                verbose_name="紹介文",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="mainuser",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="メインユーザー",
            ),
        ),
    ]
