# Generated by Django 5.0.4 on 2024-04-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0006_alter_account_detail_alter_account_hobby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="detail",
            field=models.CharField(
                choices=[
                    ("中学生", "中学生"),
                    ("高校生", "高校生"),
                    ("社会人", "社会人"),
                    ("・・・・", "・・・・"),
                    ("大学生", "大学生"),
                    ("小学生", "小学生"),
                ],
                default="・・・・",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="hobby",
            field=models.CharField(
                choices=[
                    ("ゲーム", "ゲーム"),
                    ("運動", "運動"),
                    ("VR/AR", "VR/AR"),
                    ("・・・・", "・・・・"),
                    ("PC", "PC"),
                    ("読書", "読書"),
                    ("TV", "TV"),
                    ("プログラミング", "プログラミング"),
                    ("映画", "映画"),
                ],
                default="・・・・",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="defult/5770f01a32c3c53e90ecda61483ccb08.jpg",
                null=True,
                upload_to="icon/",
                verbose_name="アイコン",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defult/sample.jpg",
                null=True,
                upload_to="backimage/",
                verbose_name="バックイメージ",
            ),
        ),
    ]
