# Generated by Django 5.0.4 on 2024-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0010_alter_account_detail_alter_account_hobby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="detail",
            field=models.CharField(default="・・・・", max_length=8),
        ),
        migrations.AlterField(
            model_name="account",
            name="hobby",
            field=models.CharField(default="・・・・", max_length=8),
        ),
    ]
