# Generated by Django 5.0.4 on 2024-04-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0011_alter_account_detail_alter_account_hobby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="icon",
            field=models.ImageField(
                default="icon/5770f01a32c3c53e90ecda61483ccb08.jpg",
                upload_to="icon/",
                verbose_name="アイコン",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default="image/sample.jpg", upload_to="image/", verbose_name="バックイメージ"
            ),
        ),
    ]
