# Generated by Django 5.0.4 on 2024-04-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0012_alter_account_icon_alter_account_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                default="・・・・",
                on_delete=django.db.models.deletion.PROTECT,
                to="xlink.category",
                verbose_name="ジャンル",
            ),
        ),
    ]
