# Generated by Django 5.0.4 on 2024-04-21 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xlink", "0013_alter_group_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="・・・・",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="xlink.category",
                verbose_name="ジャンル",
            ),
        ),
    ]
